---
development:
  cloud_name: hitfvdqa2
  api_key: '483739897286391'
  api_secret: nHetrE49ekN07Ev5VY1AicTgtf0
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hitfvdqa2
  api_key: '483739897286391'
  api_secret: nHetrE49ekN07Ev5VY1AicTgtf0
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hitfvdqa2
  api_key: '483739897286391'
  api_secret: nHetrE49ekN07Ev5VY1AicTgtf0
  enhance_image_tag: true
  static_image_support: false
